CREATE TABLE IF NOT EXISTS properties (
  id TEXT PRIMARY KEY,
  external_id TEXT,
  name TEXT NOT NULL,
  asset_type TEXT DEFAULT 'Student Housing',
  total_beds INTEGER DEFAULT 0,
  market TEXT,
  target_occupancy DOUBLE PRECISION DEFAULT 0,
  competitor_names TEXT,
  competitor_urls TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS monthly_records (
  id TEXT PRIMARY KEY,
  property_id TEXT NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
  month TEXT NOT NULL,
  revenue TEXT,
  expenses TEXT,
  occupancy DOUBLE PRECISION DEFAULT 0,
  preleased_beds INTEGER DEFAULT 0,
  uploaded_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS weekly_prelease (
  id TEXT PRIMARY KEY,
  property_id TEXT NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
  date TEXT NOT NULL,
  beds_leased INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS comp_pricing (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_name TEXT,
  floor_plan TEXT,
  rent DOUBLE PRECISION,
  date TEXT
);

CREATE TABLE IF NOT EXISTS weekly_prelease_snapshots (
  id TEXT PRIMARY KEY,
  property_id TEXT NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
  week_ending_date TEXT NOT NULL,
  total_beds INTEGER NOT NULL,
  preleased_beds INTEGER NOT NULL,
  prelease_pct DOUBLE PRECISION NOT NULL,
  source_system TEXT NOT NULL,
  source_ref TEXT,
  data_quality TEXT NOT NULL DEFAULT 'valid',
  note TEXT,
  ingested_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(property_id, week_ending_date)
);

CREATE INDEX IF NOT EXISTS idx_weekly_prelease_snapshots_property_week
  ON weekly_prelease_snapshots(property_id, week_ending_date DESC);

CREATE TABLE IF NOT EXISTS weekly_prelease_audit (
  id TEXT PRIMARY KEY,
  snapshot_id TEXT NOT NULL REFERENCES weekly_prelease_snapshots(id) ON DELETE CASCADE,
  action TEXT NOT NULL,
  old_value TEXT,
  new_value TEXT,
  actor TEXT NOT NULL,
  reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS concession_history (
  id TEXT PRIMARY KEY,
  property_id TEXT NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
  snapshot_date TEXT NOT NULL,
  promo_count INTEGER NOT NULL DEFAULT 0,
  avg_rent DOUBLE PRECISION NOT NULL DEFAULT 0,
  source_system TEXT NOT NULL DEFAULT 'market_scan',
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(property_id, snapshot_date)
);

CREATE INDEX IF NOT EXISTS idx_concession_history_property_date
  ON concession_history(property_id, snapshot_date ASC);
